### PR TITLE
Refactor SQL Schema Migration

### PR DESCRIPTION
**Pull request by sagar-patel-sls**
Refactor the code that uses sql-migrate using `github.com/golang-migrate/migrate/v4/cmd/migrate`

### CODE REVIEW

**Comment by sagar-patel-sls** [comment]
@brocaar Please review this change

**Comment by brocaar** [comment]
I have merged the `master` branch into this PR as there was a merge conflict.

**Comment by brocaar** [comment]
There is an import cycle:

```
package github.com/brocaar/chirpstack-network-server/internal/storage (test)
	imports github.com/brocaar/chirpstack-network-server/internal/test
	imports github.com/brocaar/chirpstack-network-server/internal/storage: import cycle not allowed in test
make: *** [Makefile:20: test] Error 1


Exited with code exit status 2
```

This is because `internal/test/test.go` now imports `internal/storage`, but some of the test-code within `internal/storage` import the `internal/test` package. I'm now fixing this.

**Comment by sagar-patel-sls** [comment]
Ohh, yes
Got your point
Thank you

**Comment by brocaar** [comment]
The above commit removes the `MustResetDB` and updates the tests that that were using this function.

**Comment by brocaar** [comment]
In the migrations I see all the statements contain `IF NOT EXISTS` / `IF EXISTS`. I would prefer we would not have this as this could silently hide some errors. Also, it doesn't seem to work as expected. I tried running this code on a database that was already migrated to the latest version and I get the following error:

```
FATA[0000] setup storage error: storage: migrate up error: migration failed: column "name" does not exist in line 0: CREATE TABLE IF NOT EXISTS gateway (
        mac bytea primary key,
        name varchar(100) unique not null,
        description text not null,
        created_at timestamp with time zone not null,
        updated_at timestamp with time zone not null,
        first_seen_at timestamp with time zone,
        last_seen_at timestamp with time zone,
        location point not null,
        altitude double precision not null
);

CREATE INDEX IF NOT EXISTS idx_gateway_name on gateway (name);
 (details: pq: column "name" does not exist)
```

What happens here is that the `gateway` table is not created as it already exists, but it tries to create an index for the `name` column as no index named `idx_gateway_name on gateway` exists. This is wrong. The reason is that over time the `name` column was removed. It was valid within the context of the complete migration, but you can't run these old statements against an already fully migrated database.

What is needed:

* Restore the SQL statements in their original form (without the `if not exists` / `if exists`)
* Create a migration script which creates the `schema_migrations` table and imports the `gorp_migrations` table into it. The `internal/migrations/code` would be useful for this, as it allows you to write a function which is only executed once (and then is logged in the `code_migration` table).

I suggest we do not drop the `gorp_migrations` table yet as it would make it more difficult when downgrading a ChirpStack version. It would be better to clean this up at the next major version.

Note that the `internal/migrations/code` imports `internal/storage` for the `Transaction` wrapper. As we probably want to run the code migration within the `internal/storage` `Setup` function after creating the DB connection but before the automigrate, I suggest to copy the `Transaction` wrapper into the `internal/migrations/code` file so that it no longer imports `internal/storage`.

**Comment by sagar-patel-sls** [comment]
Thanks for the review,
I will update the code and add commit to this PR

**Comment by brocaar** [comment]
Thanks @sagar-patel-sls :+1:

**Comment by sagar-patel-sls** [comment]
> Create a migration script which creates the schema_migrations table and imports the gorp_migrations table into it. 
@brocaar got your point but both table schemas were different so how can we update `schema_migrations` based on `gorp_migrations`? any idea

**Comment by sagar-patel-sls** [comment]
@brocaar 
i think we need to take all the **0058** `gorp_migration` migration files in the current migration

what did you say?

**Comment by sagar-patel-sls** [comment]
@brocaar 
>Restore the SQL statements in their original form (without the if not exists / if exists)

I think we need to keep  `if not exists / if exists` bcoz I got the below error with exiting migrated to the latest database

```
fatal msg="setup storage error: storage: migrate up error: migration failed: relation "gateway" already exists in line 0: 
create table gateway (
        mac bytea primary key,
	name varchar(100) unique not null,
	description text not null,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null,
	first_seen_at timestamp with time zone,
	last_seen_at timestamp with time zone,
	location point,
	altitude double precision);
	create index idx_gateway_name on gateway (name);
	create index idx_gateway_created_at on gateway (created_at);
	create index idx_gateway_updated_at on gateway (updated_at);
	create index idx_gateway_first_seen_at on gateway (first_seen_at);
	create index idx_gateway_last_seen_at on gateway (last_seen_at);
	
create table gateway_stats (
	id bigserial primary key,
	mac bytea not null references gateway on delete cascade,
	"timestamp" timestamp with time zone not null,
	"interval" varchar(10) not null,
	rx_packets_received int not null,
	rx_packets_received_ok int not null,
	tx_packets_received int not null,
	tx_packets_emitted int not null,
	unique (mac, "timestamp", "interval"));
	create index idx_gateway_stats_mac on gateway_stats (mac);
	create index idx_gateway_stats_timestamp on gateway_stats ("timestamp");
	create index idx_gateway_stats_interval on gateway_stats ("interval"); 
	(details: pq: relation "gateway" already exists)"
```

**Comment by brocaar** [comment]
The reason for this is that it doesn't detect that the migration was
already applied, it should not try to re-apply this migration. So it is
good that it fails this way, as it indicates that there is an issue with
the history table migration.

If you get stuck at this, then please commit and push the migrations
without if not exists / if exists + the history migration code you have so
far and I can look into it later.

**Comment by sagar-patel-sls** [comment]
@brocaar `schema_migrations` table is automatically created so I didn't create a script for this table.
Thanks

**Comment by sagar-patel-sls** [comment]
> I suggest to copy the `Transaction` wrapper into the `internal/migrations/code` file so that it no longer imports `internal/storage`.

I got your point due to circular dependency we can use `Transaction` wrapper into the `internal/migrations/code` file but we need to change in whole `code` package

**Comment by brocaar** [comment]
I'm back on this again :)

> schema_migrations table is automatically created so I didn't create a script for this table.

But what we need to do is make sure that the state from `gorp_migrations` is migrated to the `schema_migrations` table, so that the new migration library knows which migrations have already been applied and which not. Else it will re-apply the migrations from `0001_....`, which is why you see the `migration failed: relation "gateway" already exists in line 0` error.

> I got your point due to circular dependency we can use the Transaction wrapper into the internal/migrations/code file but we need to change the whole code package?

As we need to create a code migration (which needs to run before the migration library) to migrate the `gorp_migrations` to `schema_migrations`, which is started in the `storage.Setup` after the DB initialization, but before the migrations library is called, we should make sure that the `internal/migrations/code` no longer imports `internal/storage`.

I will look into this :)

**Comment by brocaar** [comment]
@sagar-patel-sls I have made some modifications, see the above commits. I have tested this on an existing (test) database and a clean database. In case of the existing database, the state from the old migration library is migrated into `schema_migrations` and only missing migrations (if any) are applied, in case of a clean database this step is skipped (as `gorp_migrations` does not exist) and all migrations are applied to the database.

Could you verify this also works for you? I'm looking forward to your feedback!

**Comment by sagar-patel-sls** [comment]
@brocaar Thanks 
okay i will verify from my end and update you

Thanks

**Comment by sagar-patel-sls** [comment]
Thanks @brocaar 
I have tested and verify golang migration and it works for me see below output logs for your reference

```
time="2021-03-25T10:51:45+05:30" level=info msg="storage: setting up storage module"
time="2021-03-25T10:51:45+05:30" level=info msg="storage: setting up Redis client"
time="2021-03-25T10:51:45+05:30" level=info msg="storage: connecting to PostgreSQL"
time="2021-03-25T10:51:46+05:30" level=info msg="migrations/code: migrating from gorp_migrations to schema_migrations" golang_schema_migrations_version=32 gorp_migrations_id=0032_increase_device_profile_reg_param_revision_len.sql
time="2021-03-25T10:51:46+05:30" level=info msg="storage: applying PostgreSQL data migrations"
time="2021-03-25T10:51:46+05:30" level=info msg="storage: PostgreSQL data migrations applied" from_version=32 to_version=33
time="2021-03-25T10:51:46+05:30" level=info msg="gateway/mqtt: connecting to mqtt broker" server="tcp://localhost:1883"
time="2021-03-25T10:51:47+05:30" level=info msg="backend/gateway: connected to mqtt server"
time="2021-03-25T10:51:47+05:30" level=info msg="gateway/mqtt: subscribing to gateway event topic" qos=0 topic=gateway/+/event/+
time="2021-03-25T10:51:47+05:30" level=info msg="api: starting network-server api server" bind="0.0.0.0:8000" ca-cert= tls-cert= tls-key=
time="2021-03-25T10:51:47+05:30" level=info msg="starting downlink device-queue scheduler"
time="2021-03-25T10:51:47+05:30" level=info msg="starting multicast scheduler"
```

we need `migrations/code/code_test.go` file because it shows circuler dependency error?

**Comment by brocaar** [comment]
> we need migrations/code/code_test.go file, because it shows circuler dependency error?

Good point, I have fixed this in the above commit. Also I have cleaned up the `Makefile` as there is no need anymore to query the `PKGS`, instead we can use `./...`. Historically this wasn't working because of vendor folder, generated api code and migration files, but this is not the case anymore :)

**Comment by brocaar** [comment]
Thanks @sagar-patel-sls for your help on this :) :+1:

**Comment by sagar-patel-sls** [comment]
Thanks @brocaar 👍 
I will make PR for `chirpstack-application-server`

**Pull request merged**
